# -*- coding: utf-8 -*-
"""normality_test_migraine_scores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pb1kslMoHSbVaiEW3RilXz_CEdBVWMOp
"""

import pandas as pd
from scipy import stats

# Load the before and after datasets (uploaded files)
before_data = pd.read_csv('/content/before.csv')  # Replace with your before file path
after_data = pd.read_csv('/content/After.csv')    # Replace with your after file path

# Check columns for clarity
print("Columns in before data:", before_data.columns)
print("Columns in after data:", after_data.columns)

# Perform Shapiro-Wilk test for normality on both before and after data for MIDAS_score and MSQ_score
shapiro_midas_before = stats.shapiro(before_data['MIDAS_score'])
shapiro_msq_before = stats.shapiro(before_data['MSQ_score'])
shapiro_midas_after = stats.shapiro(after_data['MIDAS_score'])
shapiro_msq_after = stats.shapiro(after_data['MSQ_score'])

# Print the Shapiro-Wilk test results
print("\nShapiro-Wilk Test Results:")
print(f"Before data - MIDAS_score: Statistic={shapiro_midas_before.statistic}, p-value={shapiro_midas_before.pvalue}")
print(f"Before data - MSQ_score: Statistic={shapiro_msq_before.statistic}, p-value={shapiro_msq_before.pvalue}")
print(f"After data - MIDAS_score: Statistic={shapiro_midas_after.statistic}, p-value={shapiro_midas_after.pvalue}")
print(f"After data - MSQ_score: Statistic={shapiro_msq_after.statistic}, p-value={shapiro_msq_after.pvalue}")

# Perform statistical tests based on normality results
# MIDAS_score before and after
if shapiro_midas_before.pvalue > 0.05 and shapiro_midas_after.pvalue > 0.05:
    print("\nMIDAS_score is normally distributed in both before and after, performing paired t-test...")
    t_stat_midas, p_value_midas = stats.ttest_rel(before_data['MIDAS_score'], after_data['MIDAS_score'])
else:
    print("\nMIDAS_score is not normally distributed in either before or after, performing Wilcoxon signed-rank test...")
    t_stat_midas, p_value_midas = stats.wilcoxon(before_data['MIDAS_score'], after_data['MIDAS_score'])

# MSQ_score before and after
if shapiro_msq_before.pvalue > 0.05 and shapiro_msq_after.pvalue > 0.05:
    print("\nMSQ_score is normally distributed in both before and after, performing paired t-test...")
    t_stat_msq, p_value_msq = stats.ttest_rel(before_data['MSQ_score'], after_data['MSQ_score'])
else:
    print("\nMSQ_score is not normally distributed in either before or after, performing Wilcoxon signed-rank test...")
    t_stat_msq, p_value_msq = stats.wilcoxon(before_data['MSQ_score'], after_data['MSQ_score'])

# Display p-values for both tests
print(f"\nPaired t-test or Wilcoxon test results:")
print(f"p-value for MIDAS_score: {p_value_midas}")
print(f"p-value for MSQ_score: {p_value_msq}")